import { z } from "zod";
import {
  SCORE_MIN,
  SCORE_MAX,
  READABILITY_LEVELS,
  MAX_SUGGESTION_LENGTH,
} from "@/lib/constants";

// ─── Atomic Sub-Schemas ─────────────────────────────────────────────

/** A bounded integer score in [0, 100]. */
const scoreSchema = z
  .number()
  .int()
  .min(SCORE_MIN)
  .max(SCORE_MAX)
  .describe("A quality score between 0 (worst) and 100 (best)");

/** A single piece of detected jargon with an optional plain-English alternative. */
const jargonEntrySchema = z.object({
  term: z.string().min(1).describe("The jargon term found in the text"),
  definition: z
    .string()
    .min(1)
    .describe("A plain-English explanation of the term"),
  occurrences: z
    .number()
    .int()
    .min(1)
    .describe("How many times this term appears"),
});

/** A side-by-side text rewrite suggestion. */
const textSuggestionSchema = z.object({
  original: z
    .string()
    .min(1)
    .max(MAX_SUGGESTION_LENGTH)
    .describe("The original text fragment"),
  improved: z
    .string()
    .min(1)
    .max(MAX_SUGGESTION_LENGTH)
    .describe("The improved, clearer version"),
  reason: z
    .string()
    .min(1)
    .max(MAX_SUGGESTION_LENGTH)
    .describe("Why this change improves clarity"),
});

/** Per-section breakdown of a page area (e.g., hero, navigation, body). */
const sectionAnalysisSchema = z.object({
  sectionName: z
    .string()
    .min(1)
    .describe("Descriptive name for the page section"),
  clarityScore: scoreSchema,
  readabilityLevel: z
    .enum(READABILITY_LEVELS)
    .describe("Flesch-Kincaid-like classification"),
  issues: z
    .array(z.string().min(1))
    .describe("List of specific clarity issues found"),
  suggestions: z
    .array(textSuggestionSchema)
    .describe("Side-by-side rewrite suggestions for this section"),
});

// ─── Top-Level Audit Report ─────────────────────────────────────────

/**
 * The complete audit report returned by the AI analysis pipeline.
 * This is the contract between the Vercel AI SDK structured output
 * and the downstream API response / PDF generator.
 */
export const AuditReportSchema = z.object({
  /** The URL that was audited. */
  targetUrl: z.string().min(1),

  /** ISO 8601 timestamp of when the audit was performed. */
  auditedAt: z.string().min(1),

  /** Overall clarity score for the entire page. */
  overallClarityScore: scoreSchema,

  /** Overall readability classification. */
  overallReadabilityLevel: z.enum(READABILITY_LEVELS),

  /** Executive summary of findings (2-4 sentences). */
  summary: z.string().min(1),

  /** Detected jargon terms across the entire page. */
  jargon: z.array(jargonEntrySchema),

  /** Per-section detailed analysis. */
  sections: z
    .array(sectionAnalysisSchema)
    .min(1)
    .describe("At least one section must be analyzed"),

  /** Global text improvement suggestions not tied to a specific section. */
  globalSuggestions: z.array(textSuggestionSchema),
});

export type AuditReport = z.infer<typeof AuditReportSchema>;
export type JargonEntry = z.infer<typeof jargonEntrySchema>;
export type TextSuggestion = z.infer<typeof textSuggestionSchema>;
export type SectionAnalysis = z.infer<typeof sectionAnalysisSchema>;

// ─── AI Output Schema (subset for the LLM — excludes runtime fields) ─

/**
 * The schema passed to the Vercel AI SDK's Output.object().
 * This omits `targetUrl` and `auditedAt` which are injected by the
 * server at runtime, not generated by the LLM.
 */
export const AiOutputSchema = AuditReportSchema.omit({
  targetUrl: true,
  auditedAt: true,
});

export type AiOutput = z.infer<typeof AiOutputSchema>;
